return {
  { module = "awaiting_pr", key = "awaiting-pr" },
  { module = "blocked", key = "blocked" },
  { module = "closed_unmerged", key = "closed-unmerged" },
  { module = "dependency_wait", key = "dependency_wait" },
  { module = "fixing", key = "fixing" },
  { module = "impl_failed", key = "impl-failed" },
  { module = "implementing", key = "implementing" },
  { module = "merge_ready", key = "merge-ready" },
  { module = "merged", key = "merged" },
  { module = "merging", key = "merging" },
  { module = "pr_open", key = "pr-open" },
  { module = "ready", key = "ready" },
  { module = "review_meta", key = "review-meta" },
  { module = "reviewing", key = "reviewing" },
  { module = "thinking", key = "thinking" },
}
