local M = {}

function M.persistence_class()
  return "saga"
end

require("core.base").install(M)
require("core.config").install(M)
require("core.strings").install(M)
require("core.commands").install(M)
require("core.github_proxy_entity_view").install(M)
require("core.branches").install(M)
require("core.parsers").install(M)
require("core.merge_gate").install(M)
require("core.queue").install(M)
require("core.logging").install(M)
require("core.error_facts").install(M)
require("core.conflict_telemetry").install(M)
require("core.state").install(M)
require("core.markers").install(M)
require("core.intake_service_class").install(M)
require("core.impl_failure").install(M)
require("core.payloads").install(M)
require("core.convergence").install(M)
require("core.decompose").install(M)
require("core.restart").install(M)
require("core.replayer").install(M)
require("core.liveness").install(M)
require("core.prompts").install(M)
require("core.intake_class").install(M)
require("core.requests").install(M)
require("core.review_meta_requests").install(M)
require("core.entity").install(M)
require("core.work_card").install(M)
require("core.dependencies").install(M)
require("core.validators").install(M)
require("core.observability").install(M)
require("core.ensure_repo").install(M)
require("core.context_bundle").install(M)
require("core.operator_commands").install(M)

return M
