return require("testkit_internal.devloop_fixtures").new({
  core = require("core"),
  state_api = require("devloop.state"),
  base_ids = require("devloop.base_ids"),
  entity_read_mocks = require("tests.entity_read_mock_helpers"),
  devloop_base = require("devloop.base"),
  payloads_builders = require("devloop.payloads.builders"),
  conv_reconcile = require("devloop.convergence.reconcile"),
  m_builders = require("devloop.markers.builders"),
  pr_safety = require("devloop.pr_safety"),
  consensus_call = require("devloop.consensus_call"),
  review_loop_department = require("departments.review_loop.main"),
  review_result_department = require("departments.review_result.main"),
  decompose_queue = "github-devloop-decompose.devloop_decompose",
  mock_merge_pr_diff_name_only = true,
})
