return {
  { module = "converge_round", key = "converge-round" },
  { module = "decomposed", key = "decomposed" },
  { module = "dependency_cycle", key = "dependency-cycle" },
  { module = "dependency_release", key = "dependency-release" },
  { module = "dependency_unresolvable", key = "dependency-unresolvable" },
  { module = "dependency_void", key = "dependency-void" },
  { module = "dependency_wait", key = "dependency-wait" },
  { module = "dependency_waiver", key = "dependency-waiver" },
  { module = "fix_reflection", key = "fix-reflection" },
  { module = "impl_failure", key = "impl-failure" },
  { module = "implement_attempt", key = "implement-attempt" },
  { module = "implementing", key = "implementing" },
  { module = "merge_gate", key = "merge-gate" },
  { module = "merge_ready", key = "merge-ready" },
  { module = "merging", key = "merging" },
  { module = "pr_link", key = "pr-link" },
  { module = "review_carry_over", key = "review-carry-over" },
  { module = "review_converge_round", key = "review-converge-round" },
  { module = "review_meta", key = "review-meta" },
  { module = "review_result", key = "review-result" },
  { module = "state", key = "state" },
}
