local strings = require("contract.strings")
local issue_create_limits = require("contract.github_issue_create").limits()

local M = {}

local issue_ref_pattern = "^([%w%._%-]+/[%w%._%-]+)#issue/(%d+)$"
local max_ref_len = 200

local function trim(value)
  return strings.trim(value)
end

local function parse_source_ref_text(value)
  local text = trim(value)
  if text == "" then
    return nil
  end
  if #text > max_ref_len or text:find("[\r\n]") ~= nil then
    return nil
  end
  local repo, number = text:match(issue_ref_pattern)
  if repo == nil or number == nil then
    return nil
  end
  return {
    kind = "external",
    ref = repo .. "#issue/" .. tostring(tonumber(number)),
  }
end

local function config_source_ref_from_text(value)
  local source_ref = parse_source_ref_text(value)
  if source_ref == nil then
    error("marketing-radar: invalid-config-ref: invalid config-ref")
  end
  return source_ref
end

local function signal_source_ref_from_text(value)
  local source_ref = parse_source_ref_text(value)
  if source_ref == nil then
    error("marketing-radar: invalid-signal-ref: invalid signal-ref")
  end
  return source_ref
end

local function line_fields(body)
  local fields = {}
  for line in tostring(body or ""):gmatch("([^\n]*)\n?") do
    if line == "" and fields._done then
      break
    end
    fields._done = line == ""
    local key, value = line:match("^([%w%-]+):%s*(.-)%s*$")
    if key ~= nil then
      fields[key] = value
    end
  end
  fields._done = nil
  return fields
end

local function same_source_ref(left, right)
  return type(left) == "table"
    and type(right) == "table"
    and left.kind == right.kind
    and left.ref == right.ref
end

function M.parse_radar_run_contract(body)
  local fields = line_fields(body)
  if fields["calendar-ref"] ~= nil and trim(fields["calendar-ref"]) ~= "" then
    return nil, "calendar-ref-present"
  end
  if fields["config-ref"] == nil and fields["signal-ref"] == nil then
    return nil, "not-radar-run"
  end
  return {
    config_source_ref = config_source_ref_from_text(fields["config-ref"]),
    signal_source_ref = signal_source_ref_from_text(fields["signal-ref"]),
  }, nil
end

function M.weekly_content_dedup_key(run_source_ref, signal_source_ref)
  local run_ref = type(run_source_ref) == "table" and run_source_ref.ref or ""
  local signal_ref = type(signal_source_ref) == "table" and signal_source_ref.ref or ""
  local prefix = "marketing-radar/weekly-content/"
  local key = prefix
    .. strings.sanitize_key(run_ref, 220)
    .. "/signal/"
    .. strings.decimal_checksum(signal_ref)
  if #key > issue_create_limits.dedup_key then
    key = key:sub(1, issue_create_limits.dedup_key)
  end
  return key
end

function M.weekly_content_body(run_source_ref, config_source_ref, signal_source_ref)
  return table.concat({
    "Weekly content issue generated by marketing-radar.",
    "",
    "Source pointers:",
    "- Run: " .. tostring(run_source_ref.ref),
    "- Config: " .. tostring(config_source_ref.ref),
    "- Signal: " .. tostring(signal_source_ref.ref),
    "",
    "Rehydrate the source issues from these pointers before making content decisions.",
  }, "\n")
end

function M.build_weekly_content_outputs(run_issue, config_issue, signal_issue)
  if type(run_issue) ~= "table" or type(run_issue.source_ref) ~= "table" then
    error("marketing-radar: missing-run-source-ref: run issue source_ref is required")
  end
  local parsed = M.parse_radar_run_contract(run_issue.body)
  if parsed == nil then
    return nil
  end
  if not same_source_ref(config_issue and config_issue.source_ref, parsed.config_source_ref) then
    error("marketing-radar: config-source-ref-mismatch: rehydrated config issue did not match config-ref")
  end
  if not same_source_ref(signal_issue and signal_issue.source_ref, parsed.signal_source_ref) then
    error("marketing-radar: signal-source-ref-mismatch: rehydrated signal issue did not match signal-ref")
  end

  local repo = tostring(run_issue.repo or parsed.config_source_ref.ref:match("^([^#]+)#issue/%d+$") or "")
  local dedup_key = M.weekly_content_dedup_key(run_issue.source_ref, parsed.signal_source_ref)
  local body = M.weekly_content_body(run_issue.source_ref, parsed.config_source_ref, parsed.signal_source_ref)
  local request = {
    schema = "github-proxy.issue-create.v1",
    repo = repo,
    title = "weekly-content: marketing-radar skeleton",
    body = body,
    labels = { "auto-twitter-marketing" },
    dedup_key = dedup_key,
    source_ref = {
      kind = run_issue.source_ref.kind,
      ref = run_issue.source_ref.ref,
    },
  }
  local receipt = {
    schema = "marketing-radar.weekly-content-generated.v1",
    repo = repo,
    run_source_ref = request.source_ref,
    config_source_ref = parsed.config_source_ref,
    signal_source_ref = parsed.signal_source_ref,
    issue_create_dedup_key = dedup_key,
    dedup_key = dedup_key .. "/receipt",
  }
  return {
    request = request,
    receipt = receipt,
  }
end

return M
